name: Build & Push Docker Images for Multiple Products

# Set a default product (change to "python" or "nodejs" as needed).
env:
  PRODUCT: eclipse-temurin

on:
  # pull_request:
  push:

jobs:
  ##########################
  # GENERATE MATRIX JOB
  ##########################
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}
    # env:
    #   PRODUCT: ${{ env.PRODUCT }}
    steps:
      - name: Generate Matrix for Supported ${{ env.PRODUCT }} Versions
        id: generate
        run: |
          # Determine API URL based on product.
          PRODUCT="${PRODUCT}"
          API_URL="https://endoflife.date/api/${PRODUCT}.json"
          echo "Fetching $PRODUCT versions from $API_URL..."
          curl -s "$API_URL" -o product.json

          current=$(date +%s)
          matrix_entries=()

          # Iterate over each release object in the JSON.
          while IFS= read -r obj; do
            cycle=$(echo "$obj" | jq -r '.cycle')
            latest=$(echo "$obj" | jq -r '.latest')
            eol=$(echo "$obj" | jq -r '.eol')

            # If an EOL date exists and is in the past, skip this release.
            if [ -n "$eol" ] && [ "$eol" != "null" ]; then
              eol_epoch=$(date -d "$eol" +%s)
              if [ "$eol_epoch" -lt "$current" ]; then
                echo "Skipping version $latest (cycle $cycle) because its EOL ($eol) is in the past."
                continue
              fi
            fi

            # For version parsing: remove build metadata if present.
            # (For eclipse-temurin, this changes "23.0.2+7" into "23.0.2")
            version_clean=$(echo "$latest" | sed -E 's/([+-]).*//')
            IFS='.' read -r major minor patch <<< "$version_clean"
            if [ -z "$minor" ]; then minor="0"; fi
            if [ -z "$patch" ]; then patch="0"; fi

            # Create a matrix entry.
            matrix_entries+=("{\"product\":\"$PRODUCT\",\"version\":\"$latest\",\"major\":\"$major\",\"minor\":\"$minor\",\"patch\":\"$patch\"}")
          done < <(jq -c '.[]' product.json)

          # Assemble the JSON matrix.
          matrix_json=$(IFS=, ; echo "{\"include\": [${matrix_entries[*]}]}")
          echo "Generated matrix: $matrix_json"
          echo "matrix=$matrix_json" >> "$GITHUB_OUTPUT"

  ##########################
  # BUILD & PUSH JOB: DEBIAN
  ##########################
  build-debian:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch latest Debian codename
        id: debian
        run: |
          echo "Fetching latest Debian codename..."
          DEBIAN_JSON=$(curl -s https://endoflife.date/api/debian.json)
          # Use the "codename" from the first object and convert to lower case.
          DEBIAN_CODENAME=$(echo "$DEBIAN_JSON" | jq -r '.[0].codename' | tr '[:upper:]' '[:lower:]')
          echo "Debian codename: $DEBIAN_CODENAME"
          echo "version=$DEBIAN_CODENAME" >> "$GITHUB_OUTPUT"

      - name: Build Docker image (Debian)
        run: |
          # Get matrix values.
          PRODUCT="${{ matrix.product }}"
          VERSION="${{ matrix.version }}"
          major="${{ matrix.major }}"
          minor="${{ matrix.minor }}"
          patch="${{ matrix.patch }}"

          # # For eclipse-temurin, convert the version to Docker tag format.
          # if [ "$PRODUCT" = "eclipse-temurin" ]; then
            DOCKER_VERSION=$(echo "$VERSION" | sed 's/+/_/')
            # this will be covered by actual Dockerfile that is repo specific
            SOURCE_IMAGE="eclipse-temurin:${DOCKER_VERSION}-jre"
          #   # Also set a default runtime path.
          #   RUNTIME_PATH="/opt/java/openjdk"
          # elif [ "$PRODUCT" = "python" ]; then
          #   SOURCE_IMAGE="python:${VERSION}"
          #   RUNTIME_PATH="/usr/local"  # (Adjust as needed)
          # elif [ "$PRODUCT" = "nodejs" ]; then
          #   SOURCE_IMAGE="node:${VERSION}"
          #   RUNTIME_PATH="/usr/local"  # (Adjust as needed)
          # else
          #   echo "Unsupported product: $PRODUCT"
          #   exit 1
          # fi

          DEBIAN_CODENAME="${{ steps.debian.outputs.version }}"

          # Construct image tags (append OS info).
          TAG_MAJOR="${major}-${DEBIAN_CODENAME}"
          TAG_MINOR="${major}.${minor}-${DEBIAN_CODENAME}"
          TAG_PATCH="${major}.${minor}.${patch}-${DEBIAN_CODENAME}"

          echo "Building Docker image for $PRODUCT version $VERSION"
          echo "Source image: $SOURCE_IMAGE"
          echo "Base image: debian:${DEBIAN_CODENAME}-slim"

          docker build \
            --build-arg SOURCE_IMAGE="$SOURCE_IMAGE" \
            --build-arg BASE_IMAGE="debian:${DEBIAN_CODENAME}" \
            --build-arg BASE_SUFFIX="-slim" \
            --build-arg DOCKER_VERSION="$DOCKER_VERSION" \
            -t your-docker-username/your-image:"$TAG_PATCH" .

          docker tag your-docker-username/your-image:"$TAG_PATCH" your-docker-username/your-image:"$TAG_MAJOR"
          docker tag your-docker-username/your-image:"$TAG_PATCH" your-docker-username/your-image:"$TAG_MINOR"

      # - name: Log in to Docker Hub (Debian)
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker images (Debian)
        run: |
          PRODUCT="${{ matrix.product }}"
          major="${{ matrix.major }}"
          minor="${{ matrix.minor }}"
          patch="${{ matrix.patch }}"
          DEBIAN_CODENAME="${{ steps.debian.outputs.version }}"

          TAG_MAJOR="${major}-${DEBIAN_CODENAME}"
          TAG_MINOR="${major}.${minor}-${DEBIAN_CODENAME}"
          TAG_PATCH="${major}.${minor}.${patch}-${DEBIAN_CODENAME}"

          echo "Pushing Docker images for $PRODUCT on Debian:"
          echo "We would need to docker push these images"
          # docker push your-docker-username/your-image:"$TAG_PATCH"
          # docker push your-docker-username/your-image:"$TAG_MAJOR"
          # docker push your-docker-username/your-image:"$TAG_MINOR"

  ##########################
  # BUILD & PUSH JOB: ALPINE
  ##########################
  build-alpine:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch latest Alpine version
        id: alpine
        run: |
          echo "Fetching latest Alpine version..."
          ALPINE_JSON=$(curl -s https://endoflife.date/api/alpine.json)
          ALPINE_VERSION=$(echo "$ALPINE_JSON" | jq -r '.[0].latest')
          echo "Alpine version: $ALPINE_VERSION"
          echo "version=$ALPINE_VERSION" >> "$GITHUB_OUTPUT"

      - name: Build Docker image (Alpine)
        run: |
          PRODUCT="${{ matrix.product }}"
          VERSION="${{ matrix.version }}"
          major="${{ matrix.major }}"
          minor="${{ matrix.minor }}"
          patch="${{ matrix.patch }}"

          # if [ "$PRODUCT" = "eclipse-temurin" ]; then
          #   DOCKER_VERSION=$(echo "$VERSION" | sed 's/+/_/')
          #   SOURCE_IMAGE="eclipse-temurin:${DOCKER_VERSION}-jre"
          #   RUNTIME_PATH="/opt/java/openjdk"
          # elif [ "$PRODUCT" = "python" ]; then
          #   SOURCE_IMAGE="python:${VERSION}"
          #   RUNTIME_PATH="/usr/local"
          # elif [ "$PRODUCT" = "nodejs" ]; then
          #   SOURCE_IMAGE="node:${VERSION}"
          #   RUNTIME_PATH="/usr/local"
          # else
          #   echo "Unsupported product: $PRODUCT"
          #   exit 1
          # fi

          ALPINE_VERSION="${{ steps.alpine.outputs.version }}"

          TAG_MAJOR="${major}-${ALPINE_VERSION}"
          TAG_MINOR="${major}.${minor}-${ALPINE_VERSION}"
          TAG_PATCH="${major}.${minor}.${patch}-${ALPINE_VERSION}"

          echo "Building Docker image for $PRODUCT version $VERSION"
          echo "Source image: $SOURCE_IMAGE"
          echo "Base image: alpine:${ALPINE_VERSION}"

          docker build \
            --build-arg SOURCE_IMAGE="$SOURCE_IMAGE" \
            --build-arg BASE_IMAGE="alpine:${ALPINE_VERSION}" \
            --build-arg BASE_SUFFIX="" \
            --build-arg RUNTIME_PATH="$RUNTIME_PATH" \
            -t your-docker-username/your-image:"$TAG_PATCH" .

          docker tag your-docker-username/your-image:"$TAG_PATCH" your-docker-username/your-image:"$TAG_MAJOR"
          docker tag your-docker-username/your-image:"$TAG_PATCH" your-docker-username/your-image:"$TAG_MINOR"

      - name: Log in to Docker Hub (Alpine)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker images (Alpine)
        run: |
          PRODUCT="${{ matrix.product }}"
          major="${{ matrix.major }}"
          minor="${{ matrix.minor }}"
          patch="${{ matrix.patch }}"
          ALPINE_VERSION="${{ steps.alpine.outputs.version }}"

          TAG_MAJOR="${major}-${ALPINE_VERSION}"
          TAG_MINOR="${major}.${minor}-${ALPINE_VERSION}"
          TAG_PATCH="${major}.${minor}.${patch}-${ALPINE_VERSION}"

          echo "Pushing Docker images for $PRODUCT on Alpine:"
          echo "We would need to docker push these images"
          # docker push your-docker-username/your-image:"$TAG_PATCH"
          # docker push your-docker-username/your-image:"$TAG_MAJOR"
          # docker push your-docker-username/your-image:"$TAG_MINOR"
