name: Build docker images

on:
  pull_request:
  push:

jobs:
  build-jvm-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: check jq version
        run: |
          jq --version
      - id: set-jvm-matrix
        run: |
          curl https://endoflife.date/api/eclipse-temurin.json -o temurin.json
          cat temurin.json
          TEMURIN_RELEASES=$(jq -c '[.[] | select(.eol > (now | strftime("%Y-%m-%d"))) | .cycle ]' temurin.json)
          echo $TEMURIN_RELEASES >> $GITHUB_OUTPUT
          echo $TEMURIN_RELEASES
          echo $GITHUB_OUTPUT
      - name: verify-matrix
        run: echo "Supported Java versions are $TEMURIN_RELEASES"
