name: Build docker images

on:
  pull_request:
  push:

jobs:
  build-jvm-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: check jq version
        run: |
          jq --version
      - id: set-jvm-matrix
        run: echo "name=version_matrix::$(curl https://endoflife.date/api/eclipse-temurin.json | jq -c '[.[] | select(.eol > (now | strftime("%Y-%m-%d"))) | .cycle ]')" >> $JAVA_VERSIONS
      - name: verify-matrix
        run: echo "Supported Java versions are $JAVA_VERSIONS"
