name: Build docker images

on:
  pull_request:
  push:

jobs:
  build:
    name: build-matrixes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        languages: ["elcipse-temurin", "python", "nodejs"]

    steps:
      - name: set-${{matrix.languages}}-matrix
        run: |
          curl https://endoflife.date/api/${{matrix.languages}}.json -o language.json
          cat language.json
          LANGUAGE_RELEASS=$(jq -c '[.[] | select(.eol > (now | strftime("%Y-%m-%d"))) | .cycle ]' language.json)
          echo "JAVA_VERSIONS=$LANGUAGE_RELEASS" >> $GITHUB_OUTPUT

          LATEST_VERSION=$(jq -c 'max_by(.releaseDate) | .cycle' language.json)
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_OUTPUT

          LTS_VERSION=$(jq -c 'first(.[] | select(.lts == true) | .cycle)' language.json)
          echo "LTS_VERSION=$LTS_VERSION" >> $GITHUB_OUTPUT
