name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      os:
        description: "Operating system to use (debian or alpine)"
        required: true
        type: string
      base_suffix:
        description: 'Suffix for the base image (e.g. "-slim" for debian, "" for alpine)'
        required: true
        type: string
      tag_prefix:
        description: 'Optional prefix to insert in image tags (e.g. "alpine-" for alpine images)'
        required: true
        type: string
      product:
        description: "Product name (e.g. eclipse-temurin)"
        required: true
        type: string
      repository_name:
        description: "Name of the repository to push images to"
        required: true
        type: string
      version:
        description: "Product version (from the matrix)"
        required: true
        type: string
      major:
        description: "Major version number"
        required: true
        type: string
      minor:
        description: "Minor version number"
        required: true
        type: string
      patch:
        description: "Patch version number"
        required: true
        type: string

      # Optional inputs
      docker_file:
        description: "Path to the Dockerfile to use"
        required: false
        type: string
        default: Dockerfile
      build_minor:
        description: "Whether to build minor versions"
        required: false
        type: boolean
        default: true
      build_patch:
        description: "Whether to build patch versions"
        required: false
        type: boolean
        default: true
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build-push:
    runs-on: ubuntu-latest
    outputs:
      os_version: ${{ steps.get_os_version.outputs.os_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch OS version
        id: get_os_version
        run: |
          if [ "${{ inputs.os }}" = "debian" ]; then
            echo "Fetching latest Debian codename..."
            OS_JSON=$(curl -s https://endoflife.date/api/debian.json)
            OS_VERSION=$(echo "$OS_JSON" | jq -r '.[0].codename' | tr '[:upper:]' '[:lower:]')
          elif [ "${{ inputs.os }}" = "alpine" ]; then
            echo "Fetching latest Alpine version..."
            OS_JSON=$(curl -s https://endoflife.date/api/alpine.json)
            OS_VERSION=$(echo "$OS_JSON" | jq -r '.[0].latest')
          else
            echo "Unsupported OS: ${{ inputs.os }}"
            exit 1
          fi
          echo "OS version: $OS_VERSION"
          echo "os_version=$OS_VERSION" >> "$GITHUB_OUTPUT"

      - name: Build Docker image
        id: build
        run: |
          PRODUCT="${{ inputs.product }}"
          REPOSITORY_NAME="${{ inputs.repository_name }}"
          VERSION="${{ inputs.version }}"
          major="${{ inputs.major }}"
          minor="${{ inputs.minor }}"
          patch="${{ inputs.patch }}"

          DOCKER_VERSION=$(echo "$VERSION" | sed 's/+/_/')
          SOURCE_IMAGE="${PRODUCT}:${DOCKER_VERSION}-jre"
          OS_VERSION="${{ steps.get_os_version.outputs.os_version }}"

          TAG_MAJOR="${major}-${{ inputs.tag_prefix }}${OS_VERSION}"
          TAG_MINOR="${major}.${minor}-${{ inputs.tag_prefix }}${OS_VERSION}"
          TAG_PATCH="${major}.${minor}.${patch}-${{ inputs.tag_prefix }}${OS_VERSION}"

          echo "Building Docker image for $PRODUCT version $VERSION"
          echo "Source image: $SOURCE_IMAGE"
          echo "Base image: ${{ inputs.os }}:${OS_VERSION}${{ inputs.base_suffix }}"

          docker build \
            --build-arg SOURCE_IMAGE="$SOURCE_IMAGE" \
            --build-arg BASE_IMAGE="${{ inputs.os }}:${OS_VERSION}" \
            --build-arg BASE_SUFFIX="${{ inputs.base_suffix }}" \
            --build-arg DOCKER_VERSION="$DOCKER_VERSION" \
            -f ${{ inputs.docker_file }} \
            -t mrbusche/${REPOSITORY_NAME}:"${TAG_MAJOR}" .

          echo "Tagging Docker images..."
          if [ "${{ inputs.build_minor }}" = "true" ]; then
            docker tag mrbusche/${REPOSITORY_NAME}:"$TAG_MAJOR" mrbusche/${REPOSITORY_NAME}:"$TAG_MINOR"
          fi
          if [ "${{ inputs.build_patch }}" = "true" ]; then
            docker tag mrbusche/${REPOSITORY_NAME}:"$TAG_MAJOR" mrbusche/${REPOSITORY_NAME}:"$TAG_PATCH"
          fi

          # Set outputs for use in later steps.
          echo "TAG_MAJOR=${TAG_MAJOR}" >> "$GITHUB_OUTPUT"
          echo "TAG_MINOR=${TAG_MINOR}" >> "$GITHUB_OUTPUT"
          echo "TAG_PATCH=${TAG_PATCH}" >> "$GITHUB_OUTPUT"
          echo "REPOSITORY_NAME=${REPOSITORY_NAME}" >> "$GITHUB_OUTPUT"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker images
        run: |
          REPOSITORY_NAME="${{ inputs.repository_name }}"
          echo "Pushing Docker images for ${RESPOSITORY_NAME} on ${{ inputs.os }}..."
          docker push mrbusche/${REPOSITORY_NAME}:"${{ steps.build.outputs.TAG_MAJOR }}"
          if [ "${{ inputs.build_minor }}" = "true" ]; then
            docker push mrbusche/${REPOSITORY_NAME}:"${{ steps.build.outputs.TAG_MINOR }}"
          fi
          if [ "${{ inputs.build_patch }}" = "true" ]; then
            docker push mrbusche/${REPOSITORY_NAME}:"${{ steps.build.outputs.TAG_PATCH }}"
          fi
